// Fixture: the everyday case (reference prototype artboard 1) — 2 repos, mixed
// coverage states, one failed run. Fully deterministic: every date is a
// hardcoded YYYY-MM-DD literal, "today" is fixed at 2026-08-23, no Date.now().
//
// Repo names are fictional: "quillbase" stands in for the private prototype
// repo (ids follow the same shape: QB-SEC-02 etc.), "novudesk" is the existing
// fictional second repo. No real URLs appear anywhere.
import type { DashboardInput } from "./dashboard-run.js";

export const populatedFixture: DashboardInput = {
  generated_at: "2026-08-23 06:14",
  engine_version: "3.0.0-dev",
  today: "2026-08-23",

  repos: [
    {
      name: "quillbase",
      pack_present: true,
      lanes: [
        {
          lane: "security",
          state: "on",
          entries: [
            {
              id: "ASVS-AUTH-01",
              title: "Account authentication endpoints",
              kind: "vector",
              area: ["app/Http/Controllers/Account*"],
              weight: "critical",
              interval_days: 7,
              owner: "security",
              last_reviewed: "2026-08-22",
            },
            {
              id: "ASVS-SESS-02",
              title: "Session issuance and rotation",
              kind: "vector",
              area: ["app/Services/Billing/*"],
              weight: "critical",
              interval_days: 7,
              owner: "security",
              last_reviewed: "2026-08-21",
            },
            {
              id: "QB-SEC-02",
              title: "Dispatch endpoint command handling",
              kind: "vector",
              area: ["app/Services/Dispatch/*"],
              weight: "critical",
              interval_days: 7,
              owner: "security",
              last_reviewed: "2026-08-22",
            },
            {
              id: "ASVS-RATE-07",
              title: "Rate limiting middleware",
              kind: "vector",
              area: ["app/Http/Middleware/*"],
              weight: "high",
              interval_days: 14,
              owner: "security",
              last_reviewed: "2026-08-09",
            },
            {
              id: "QB-SEC-04",
              title: "Triage Gate prompt injection surface",
              kind: "vector",
              area: ["app/Services/TriageGate/*"],
              weight: "high",
              interval_days: 14,
              owner: "security",
              last_reviewed: "2026-06-27",
            },
            {
              id: "QB-SEC-06",
              title: "Webhook signature validation window",
              kind: "vector",
              area: ["app/Services/Webhooks/*"],
              weight: "medium",
              interval_days: 30,
              owner: "security",
              last_reviewed: "2026-08-18",
            },
          ],
        },
        {
          lane: "design",
          state: "on",
          entries: [
            {
              id: "FLOW-01",
              title: "Checkout",
              kind: "flow",
              area: ["/checkout (FLOW-01)"],
              weight: "critical",
              interval_days: 7,
              owner: "design",
              last_reviewed: "2026-08-20",
            },
            {
              id: "FLOW-02",
              title: "Signup",
              kind: "flow",
              area: ["/signup (FLOW-02)"],
              weight: "high",
              interval_days: 14,
              owner: "design",
            },
            {
              id: "FLOW-03",
              title: "Account settings",
              kind: "flow",
              area: ["/settings (FLOW-03)"],
              weight: "medium",
              interval_days: 30,
              owner: "design",
            },
          ],
        },
      ],
      findings: [
        {
          dedupe_key: {
            surface: "QB-SEC-02",
            symptom: "dispatch endpoint accepts replayed signed commands",
            root_cause: "missing nonce/timestamp check on command envelope",
          },
          severity: "critical",
          confidence: "high",
          needs_human_verification: true,
          first_seen: "2026-08-17",
          last_seen: "2026-08-23",
          run_id: "20260817-0611-security-quillbase",
          repo: "quillbase",
          lane: "security",
          title: "Command replay exposure on dispatch endpoints",
          age_days: 6,
          no_movement: true,
        },
        {
          dedupe_key: {
            surface: "FLOW-01",
            symptom: "card errors clear the entire checkout form",
            root_cause: "form re-renders from scratch on validation error",
          },
          severity: "medium",
          confidence: "medium",
          needs_human_verification: false,
          first_seen: "2026-08-20",
          last_seen: "2026-08-20",
          run_id: "20260820-0609-design-quillbase",
          repo: "quillbase",
          lane: "design",
          title: "Checkout: card errors clear the whole form",
          anchor: "friction_delta",
          measured: "+4 steps",
          evidence: "evidence/quillbase/f3a91c02.png",
          evidence_present: true,
        },
        {
          dedupe_key: {
            surface: "QB-SEC-06",
            symptom: "webhook accepts signatures well past intended window",
            root_cause: "signature timestamp tolerance set too permissively",
          },
          severity: "medium",
          confidence: "medium",
          needs_human_verification: false,
          first_seen: "2026-08-10",
          last_seen: "2026-08-18",
          run_id: "20260810-0605-security-quillbase",
          repo: "quillbase",
          lane: "security",
          title: "Webhook signature window too permissive",
          filed: "QB-318",
        },
      ],
      suppressions: [
        {
          dedupe_key: {
            surface: "QB-SEC-03",
            symptom: "open redirect on legacy return_to param",
            root_cause: "redirect target not re-validated after auth callback",
          },
          reason: "redirect re-validation",
          expires: "2026-09-15",
          approved_by: "anyone",
          filed: "QB-291",
        },
      ],
      run_records: [
        // One run record per ok cost row above — every captured cost joins a
        // recorded run, so the trends header count matches the series.
        ...(
          [
            ["20260728-0610-security-quillbase", "2026-07-28", "06:10"],
            ["20260731-0605-security-quillbase", "2026-07-31", "06:05"],
            ["20260804-0608-security-quillbase", "2026-08-04", "06:08"],
            ["20260809-0602-security-quillbase", "2026-08-09", "06:02"],
            ["20260812-0611-security-quillbase", "2026-08-12", "06:11"],
            ["20260817-0609-security-quillbase", "2026-08-17", "06:09"],
            ["20260821-0603-security-quillbase", "2026-08-21", "06:03"],
          ] as const
        ).map(([run_id, date, hm]) => ({
          run_id,
          ts: `${date}T${hm}:00Z`,
          date,
          lane: "security" as const,
          pack_sha: "a1b2c3d",
          selected: 6,
          reviewed: 6,
          findings_created: 2,
          confirmed: 1,
          rejected_tier1: 1,
          rejected_tier2: 0,
          suppressed: 0,
          usage_by_model: { "claude-opus": 0.3, "claude-haiku": 0.05 },
          usage_spent: 3.5,
          elapsed: 580,
        })),
        {
          run_id: "20260823-0612-security-quillbase",
          ts: "2026-08-23T06:12:00Z",
          date: "2026-08-23",
          lane: "security",
          pack_sha: "a1b2c3d",
          selected: 6,
          reviewed: 6,
          findings_created: 1,
          confirmed: 1,
          rejected_tier1: 2,
          rejected_tier2: 1,
          suppressed: 1,
          usage_by_model: { "claude-opus": 0.32, "claude-sonnet": 0.14 },
          usage_spent: 4.61,
          elapsed: 612,
        },
      ],
      daily: [
        {
          date: "2026-07-28",
          lane: "security",
          ts: "2026-07-28T06:15:00Z",
          runs: 1,
          surfaces_total: 6,
          surfaces_green: 4,
          surfaces_stale: 1,
          surfaces_overdue: 1,
          open_findings: 0,
          coverage_freshness_pct: 71,
          median_staleness_ratio: 0.4,
          fpr_7d: 31,
          fpr_30d: 34,
        },
        {
          date: "2026-07-31",
          lane: "security",
          ts: "2026-07-31T06:15:00Z",
          runs: 1,
          surfaces_total: 6,
          surfaces_green: 4,
          surfaces_stale: 1,
          surfaces_overdue: 1,
          open_findings: 0,
          coverage_freshness_pct: 74,
          median_staleness_ratio: 0.38,
          fpr_7d: 28,
          fpr_30d: 31,
        },
        {
          date: "2026-08-04",
          lane: "security",
          ts: "2026-08-04T06:15:00Z",
          runs: 1,
          surfaces_total: 6,
          surfaces_green: 4,
          surfaces_stale: 1,
          surfaces_overdue: 1,
          open_findings: 0,
          coverage_freshness_pct: 74,
          median_staleness_ratio: 0.35,
          fpr_7d: 24,
          fpr_30d: 27,
        },
        {
          date: "2026-08-09",
          lane: "security",
          ts: "2026-08-09T06:15:00Z",
          runs: 1,
          surfaces_total: 6,
          surfaces_green: 5,
          surfaces_stale: 0,
          surfaces_overdue: 1,
          open_findings: 0,
          coverage_freshness_pct: 79,
          median_staleness_ratio: 0.3,
          fpr_7d: 22,
          fpr_30d: 25,
        },
        {
          date: "2026-08-12",
          lane: "security",
          ts: "2026-08-12T06:15:00Z",
          runs: 1,
          surfaces_total: 6,
          surfaces_green: 5,
          surfaces_stale: 0,
          surfaces_overdue: 1,
          open_findings: 1,
          coverage_freshness_pct: 83,
          median_staleness_ratio: 0.28,
          fpr_7d: 19,
          fpr_30d: 22,
        },
        {
          date: "2026-08-17",
          lane: "security",
          ts: "2026-08-17T06:15:00Z",
          runs: 1,
          surfaces_total: 6,
          surfaces_green: 5,
          surfaces_stale: 0,
          surfaces_overdue: 1,
          open_findings: 1,
          coverage_freshness_pct: 81,
          median_staleness_ratio: 0.3,
          fpr_7d: 24,
          fpr_30d: 27,
        },
        {
          date: "2026-08-21",
          lane: "security",
          ts: "2026-08-21T06:15:00Z",
          runs: 1,
          surfaces_total: 6,
          surfaces_green: 5,
          surfaces_stale: 0,
          surfaces_overdue: 1,
          open_findings: 2,
          coverage_freshness_pct: 86,
          median_staleness_ratio: 0.27,
          fpr_7d: 26,
          fpr_30d: 29,
        },
        {
          date: "2026-08-23",
          lane: "security",
          ts: "2026-08-23T06:15:00Z",
          runs: 1,
          surfaces_total: 6,
          surfaces_green: 5,
          surfaces_stale: 0,
          surfaces_overdue: 1,
          open_findings: 2,
          coverage_freshness_pct: 88,
          median_staleness_ratio: 0.25,
          fpr_7d: 29,
          fpr_30d: 32,
        },
      ],
      costs: [
        {
          run_id: "20260728-0610-security-quillbase",
          lane: "security",
          date: "2026-07-28",
          ts: "2026-07-28T06:10:00Z",
          usd: 1.84,
          input_tokens: 210000,
          output_tokens: 9000,
          cache_read_tokens: 40000,
          cache_creation_tokens: 12000,
          source: "cli-json",
          status: "ok",
        },
        {
          run_id: "20260731-0605-security-quillbase",
          lane: "security",
          date: "2026-07-31",
          ts: "2026-07-31T06:05:00Z",
          usd: 2.1,
          input_tokens: 232000,
          output_tokens: 9600,
          cache_read_tokens: 44000,
          cache_creation_tokens: 12500,
          source: "cli-json",
          status: "ok",
        },
        {
          run_id: "20260804-0608-security-quillbase",
          lane: "security",
          date: "2026-08-04",
          ts: "2026-08-04T06:08:00Z",
          usd: 1.96,
          input_tokens: 221000,
          output_tokens: 9300,
          cache_read_tokens: 42000,
          cache_creation_tokens: 12200,
          source: "cli-json",
          status: "ok",
        },
        {
          run_id: "20260809-0602-security-quillbase",
          lane: "security",
          date: "2026-08-09",
          ts: "2026-08-09T06:02:00Z",
          usd: 3.42,
          input_tokens: 340000,
          output_tokens: 14200,
          cache_read_tokens: 61000,
          cache_creation_tokens: 18800,
          source: "cli-json",
          status: "ok",
        },
        {
          run_id: "20260812-0611-security-quillbase",
          lane: "security",
          date: "2026-08-12",
          ts: "2026-08-12T06:11:00Z",
          usd: 3.88,
          input_tokens: 361000,
          output_tokens: 15100,
          cache_read_tokens: 64000,
          cache_creation_tokens: 19700,
          source: "cli-json",
          status: "ok",
        },
        {
          run_id: "20260817-0609-security-quillbase",
          lane: "security",
          date: "2026-08-17",
          ts: "2026-08-17T06:09:00Z",
          usd: 4.12,
          input_tokens: 372000,
          output_tokens: 15600,
          cache_read_tokens: 66000,
          cache_creation_tokens: 20100,
          source: "cli-json",
          status: "ok",
        },
        {
          run_id: "20260821-0603-security-quillbase",
          lane: "security",
          date: "2026-08-21",
          ts: "2026-08-21T06:03:00Z",
          usd: 4.05,
          input_tokens: 368000,
          output_tokens: 15400,
          cache_read_tokens: 65000,
          cache_creation_tokens: 19900,
          source: "cli-json",
          status: "ok",
        },
        {
          run_id: "20260823-0612-security-quillbase",
          lane: "security",
          date: "2026-08-23",
          ts: "2026-08-23T06:12:00Z",
          usd: 4.61,
          input_tokens: 402000,
          output_tokens: 16800,
          cache_read_tokens: 70000,
          cache_creation_tokens: 21500,
          source: "cli-json",
          status: "ok",
        },
        {
          run_id: "20260823-0340-design-quillbase",
          lane: "design",
          date: "2026-08-23",
          ts: "2026-08-23T03:40:00Z",
          usd: 0.62,
          input_tokens: 58000,
          output_tokens: 900,
          cache_read_tokens: 8000,
          cache_creation_tokens: 3000,
          source: "cli-json",
          status: "error",
          terminal_reason: "api_error",
        },
      ],
    },
    {
      name: "novudesk",
      pack_present: true,
      lanes: [
        {
          lane: "security",
          state: "on",
          entries: [
            {
              id: "ASVS-AUTH-01",
              title: "Session controller authentication",
              kind: "vector",
              area: ["app/controllers/sessions_controller.rb"],
              weight: "critical",
              interval_days: 7,
              owner: "security",
              last_reviewed: "2026-08-19",
            },
            {
              id: "ND-SEC-04",
              title: "Triage Gate service boundary",
              kind: "vector",
              area: ["app/services/triage_gate/*"],
              weight: "high",
              interval_days: 14,
              owner: "security",
              last_reviewed: "2026-08-05",
            },
            {
              id: "ND-SEC-07",
              title: "Triage Gate review queue output handling",
              kind: "vector",
              area: ["app/services/triage_gate/review_queue.rb"],
              weight: "medium",
              interval_days: 30,
              owner: "security",
              last_reviewed: "2026-06-22",
            },
          ],
        },
        {
          lane: "design",
          state: "disabled",
          entries: [],
        },
      ],
      findings: [],
      suppressions: [],
      run_records: [
        {
          run_id: "20260821-0700-security-novudesk",
          ts: "2026-08-21T07:00:00Z",
          date: "2026-08-21",
          lane: "security",
          pack_sha: "e5f6a7b",
          selected: 3,
          reviewed: 3,
          findings_created: 0,
          confirmed: 0,
          rejected_tier1: 1,
          rejected_tier2: 0,
          suppressed: 0,
          usage_by_model: { "claude-sonnet": 0.09 },
          usage_spent: 2.98,
          elapsed: 401,
        },
      ],
      daily: [],
      costs: [
        {
          run_id: "20260821-0700-security-novudesk",
          lane: "security",
          date: "2026-08-21",
          ts: "2026-08-21T07:00:00Z",
          usd: 2.98,
          input_tokens: 198000,
          output_tokens: 8200,
          cache_read_tokens: 31000,
          cache_creation_tokens: 9600,
          source: "cli-json",
          status: "ok",
        },
      ],
    },
  ],

  digests: [
    {
      repo: "quillbase",
      generated_at: "2026-08-23 06:14",
      runs_behind: 0,
      age_days: 0,
      items: [
        {
          repo: "quillbase",
          text: "Verify and prioritise `QB-SEC-02` (dispatch endpoint command replay) — critical, awaiting human verification since 2026-08-17.",
        },
        {
          repo: "quillbase",
          text: "Decide whether the Triage Gate cluster gets a focused pass — `QB-SEC-04` overdue 57d and the LLM-content surface is the thinnest-covered area across both repos.",
        },
      ],
    },
    {
      repo: "novudesk",
      generated_at: "2026-08-21 07:02",
      runs_behind: 2,
      age_days: 2,
      items: [
        {
          repo: "novudesk",
          text: "Approve or reject 2 proposed registry entries from gardening (`app/services/export/*`, `app/jobs/*`).",
        },
      ],
    },
  ],

  orphan_run_dirs: [
    { path: "novudesk/.nightshift/.run/20260812-0700-security/", age_days: 11 },
  ],

  evidence_stats: { files: 4, bytes: 1258291, unreferenced: 0 },
};
